language: java
jdk:
- oraclejdk8
- oraclejdk7
env:
  global:
  - secure: JH30TVs4s3V2rJ6WCg6Ycoreb/EH6ugnOI0IGLrz93iEkDc71AFpPotCgyjLFqoGv2np2Z2Dym0Q8kqCoC4VmivNWQcWW6JHse+iqpuA6DQQQ5+s6CEXpYxtgtZUhjOuOj+dw6CyJGwiZgIiokj4Zov1mxjdRro0PNKrfVZCx18=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
after_success:
- ".utility/push-output-to-ghpages.sh"
