dist: trusty

language: java
jdk:
  - oraclejdk8
  - openjdk10
  - openjdk11
    
env:
  global:
  - secure: JH30TVs4s3V2rJ6WCg6Ycoreb/EH6ugnOI0IGLrz93iEkDc71AFpPotCgyjLFqoGv2np2Z2Dym0Q8kqCoC4VmivNWQcWW6JHse+iqpuA6DQQQ5+s6CEXpYxtgtZUhjOuOj+dw6CyJGwiZgIiokj4Zov1mxjdRro0PNKrfVZCx18=
addons:
  chrome: stable
before_install:
  #Temp workaround to public key error on sudo apt-get update
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver    
before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_success:
  - ".utility/push-output-to-ghpages.sh"